"""initial schema

Revision ID: 153d63076ab2
Revises: 
Create Date: 2026-01-21 06:27:43.467128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '153d63076ab2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hosts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('os_name', sa.String(length=255), nullable=True),
    sa.Column('os_version', sa.String(length=255), nullable=True),
    sa.Column('cpu_model', sa.String(length=255), nullable=True),
    sa.Column('cpu_cores', sa.Integer(), nullable=True),
    sa.Column('cpu_threads', sa.Integer(), nullable=True),
    sa.Column('ram_total_mb', sa.Integer(), nullable=True),
    sa.Column('gpu_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hosts_hostname'), 'hosts', ['hostname'], unique=True)
    op.create_table('metrics_cpu',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usage_percent', sa.Float(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('freq_mhz', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_cpu_host_id'), 'metrics_cpu', ['host_id'], unique=False)
    op.create_index('ix_metrics_cpu_host_ts_desc', 'metrics_cpu', ['host_id', 'ts'], unique=False)
    op.create_index(op.f('ix_metrics_cpu_ts'), 'metrics_cpu', ['ts'], unique=False)
    op.create_table('metrics_gpu',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('utilization_percent', sa.Float(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('memory_used_mb', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_gpu_host_id'), 'metrics_gpu', ['host_id'], unique=False)
    op.create_index('ix_metrics_gpu_host_ts_desc', 'metrics_gpu', ['host_id', 'ts'], unique=False)
    op.create_index(op.f('ix_metrics_gpu_ts'), 'metrics_gpu', ['ts'], unique=False)
    op.create_table('metrics_ram',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_mb', sa.Integer(), nullable=False),
    sa.Column('available_mb', sa.Integer(), nullable=False),
    sa.Column('usage_percent', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['host_id'], ['hosts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_metrics_ram_host_id'), 'metrics_ram', ['host_id'], unique=False)
    op.create_index('ix_metrics_ram_host_ts_desc', 'metrics_ram', ['host_id', 'ts'], unique=False)
    op.create_index(op.f('ix_metrics_ram_ts'), 'metrics_ram', ['ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_metrics_ram_ts'), table_name='metrics_ram')
    op.drop_index('ix_metrics_ram_host_ts_desc', table_name='metrics_ram')
    op.drop_index(op.f('ix_metrics_ram_host_id'), table_name='metrics_ram')
    op.drop_table('metrics_ram')
    op.drop_index(op.f('ix_metrics_gpu_ts'), table_name='metrics_gpu')
    op.drop_index('ix_metrics_gpu_host_ts_desc', table_name='metrics_gpu')
    op.drop_index(op.f('ix_metrics_gpu_host_id'), table_name='metrics_gpu')
    op.drop_table('metrics_gpu')
    op.drop_index(op.f('ix_metrics_cpu_ts'), table_name='metrics_cpu')
    op.drop_index('ix_metrics_cpu_host_ts_desc', table_name='metrics_cpu')
    op.drop_index(op.f('ix_metrics_cpu_host_id'), table_name='metrics_cpu')
    op.drop_table('metrics_cpu')
    op.drop_index(op.f('ix_hosts_hostname'), table_name='hosts')
    op.drop_table('hosts')
    # ### end Alembic commands ###
